image: nvcr.io/nvidia/pytorch:21.10-py3
port: 8501
command:
  - /bin/sh
  - '-c'
  - |
    cd /opt/repos/repo
    pip install -r requirements.txt
    streamlit run app.py
models:
  - id: mo6l0m1nq4zqrp
    path: /opt/models
repositories:
  dataset: dshxxif865nmrg4
  mountPath: /opt/repos
  repositories:
    - url: https://github.com/joshua-paperspace/ResNet-PyTorch-Example
      name: repo
      ref: main
resources:
  replicas: 1
  instanceType: C4
